FuensantaBundle\Entity\Article:
    type: entity
    table: article
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: false
            length: 200
            options:
                fixed: false
        content:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        date:
            type: date
            nullable: false
    lifecycleCallbacks: {  }
