FuensantaBundle\Entity\Event:
    type: entity
    table: event
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        type:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        description:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
        date:
            type: date
            nullable: false
        time:
            type: time
            nullable: false
    lifecycleCallbacks: {  }
