fuensanta_homepage:
    path:     /
    defaults: { _controller: FuensantaBundle:Default:index }

fuensanta_articleList:
  path: /articles
  defaults: { _controller: FuensantaBundle:Default:articlesList }

Fuensanta_fairsList:
  path:  /fairs
  defaults: { _controller: FuensantaBundle:Default:fairsList }

fuensanta_eventsList:
  path:   /events/{fair_id}
  defaults: { _controller: FuensantaBundle:Default:eventsList }